version: '3.9'

services:
    
    db:  
        image: mysql
        container_name: ${APP_NAME}-db
        hostname: ${APP_NAME}-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${APP_NAME}
        restart: unless-stopped
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - default

    app:
        build:
            context: .
            dockerfile:  Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION}
        container_name: ${APP_NAME}-app
        hostname: ${APP_NAME}-app
        restart: unless-stopped
        volumes:
            - ../src/:/var/www/html
        ports:
            - "${APP_PORT}:8000"
        depends_on:
            - db
        networks:
            - default
            
volumes:
    db-data:
        name: db-${APP_NAME}-data

networks:
    default: